[tools]
darklua = { github = "seaofvoices/darklua", version = "=0.11.3" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.20.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.13.0" }
