[tools]
darklua = { github = "seaofvoices/darklua", version = "=0.11.3" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
selene = { github = "Kampfkarren/selene", version = "0.20.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.13.0" }
rojo = { github = "rojo-rbx/rojo", version = "=7.4.0-rc3" }
